---
- name: Repository update & Install/Start/Enable Apache with PHP support
  hosts: all
  become: true
  pre_tasks:


  - name: Install Updates on rhel9
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"
 
  - name: Install Updates on debian11
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"


- hosts: web_servers
  become: true
  tasks: 

  - name: Install Apache & PHP on debian11
    apt: 
      name: 
        - apache2
        - libapache2-mod-php  
      state: latest
    when: ansible_distribution == "Debian"

  - name: Install Apache & PHP on rhel9
    dnf:
      name:
        - httpd
        - php
      state: latest  
    when: ansible_distribution == "RedHat"


- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb package on rhel9
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat"  

  - name: Install mariadb package on debian11
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"  

- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    package:
      name: samba
      state: latest
...
