---
- name: Repository update & Install/Start/Enable Apache with PHP support
  hosts: all
  become: true
  pre_tasks:


  - name: Install Updates on rhel9
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"
 
  - name: Install Updates on debian11
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

      
- hosts: workstations
  become: true
  tasks:

  - name: Install unzip
    package:
      name: unzip

  - name: Install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: web_servers
  become: true
  tasks: 

  - name: Install Apache & PHP on debian11
    tags: apache,apache2,debian
    apt: 
      name: 
        - apache2
        - libapache2-mod-php  
      state: latest
    when: ansible_distribution == "Debian"

  - name: Install Apache & PHP on rhel9
    tags: apache,rehat,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest  
    when: ansible_distribution == "RedHat"

  - name: Start httpd on rhel9
    tags: apache,redhat,httpd
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "RedHat"

  - name: change e-mail address for ServerAdmin in httpd.conf file on rhel9
    tags: apache,redhat,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "RedHat"
    register: httpd

  - name: Restart httpd on rhel9
    tags: apache,redhat,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: Copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb package on rhel9
    tags: redhat,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat"  

  - name: Install mariadb package on debian11
    tags: db,mariadb,debian
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"  

- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    tags: samba
    package:
      name: samba
      state: latest
...
