- name: Install mariadb server package on rhel9
  tags: redhat,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "RedHat"

- name: Install mariadb server package on debian11
  tags: db,mariadb,debian
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Debian"

